#!/usr/bin/env python3
"""Convert usnlogo.png to an RGB565 big-endian C header for the ST7735R (rotated 160x128)."""

from PIL import Image
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(SCRIPT_DIR, '..', 'usnlogo.png')
OUT = os.path.join(SCRIPT_DIR, '..', 'src', 'usnlogo.h')

img = Image.open(SRC).convert('RGB')
new_w, new_h = img.size  # 160x128, no scaling needed
print(f"Using original size {new_w}x{new_h}")

y_offset = 0

# Convert each pixel to RGB565 big-endian (2 bytes: high byte first)
data = []
for y in range(new_h):
    for x in range(new_w):
        r, g, b = img.getpixel((x, y))
        rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        data.append((rgb565 >> 8) & 0xFF)
        data.append(rgb565 & 0xFF)

with open(OUT, 'w') as f:
    f.write('/* Auto-generated by scripts/convert_logo.py -- do not edit */\n')
    f.write('#pragma once\n')
    f.write('#include <stdint.h>\n\n')
    f.write(f'#define USNLOGO_WIDTH   {new_w}U\n')
    f.write(f'#define USNLOGO_HEIGHT  {new_h}U\n\n')
    f.write(f'/* RGB565 big-endian pixel data ({new_w}x{new_h}, {len(data)} bytes) */\n')
    f.write(f'static const uint8_t usnlogo_rgb565[{len(data)}U] = {{\n')
    for i, byte in enumerate(data):
        if i % 16 == 0:
            f.write('    ')
        f.write(f'0x{byte:02X}')
        if i < len(data) - 1:
            f.write(',')
        if (i + 1) % 16 == 0 or i == len(data) - 1:
            f.write('\n')
        else:
            f.write(' ')
    f.write('};\n')

print(f"Written {len(data)} bytes to {OUT}")
print(f"Display at x=0, y={y_offset} (centered)")
