# OV7670 FIFO Camera Demo
CONFIG_GPIO=y
CONFIG_I2C=y

# Serial console (required for any UART output on nRF54L15)
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_PRINTK=y

# Logging
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_BACKEND_UART=y

CONFIG_MAIN_STACK_SIZE=4096
